name: rice_quality_scanning
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.16.0 <3.0.0"

dependencies:
  bloc: ^8.0.3
  cloud_firestore: ^3.1.15
  cupertino_icons: ^1.0.2
  email_validator: ^2.0.1
  equatable: ^2.0.3
  firebase_auth: ^3.3.18
  firebase_core: ^1.17.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  flutter_neumorphic: ^3.0.3
  google_fonts: ^2.3.1
  http: ^0.13.4
  image_picker: ^0.8.5+3
  intl: ^0.17.0
  lottie: ^1.3.0
  path: ^1.6.2
  path_provider: ^2.0.9
  percent_indicator: ^4.0.0

dev_dependencies:
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/
